import type { BroadcastTemplate } from '@/shared/preview/templateContract'

export const personTemplate: BroadcastTemplate = {
    id: 'person',
    name: 'Person Lower Third',
    canvas: {
        width: 1920,
        height: 1080,
        background: {
            type: 'color',
            value: '#101214',
        },
    },
    layers: [
        {
            id: 'person-name-panel',
            type: 'shape',
            shapeType: 'rect',
            x: 112,
            y: 792,
            width: 960,
            height: 82,
            zIndex: 1,
            fill: {
                type: 'solid',
                value: '#173a73',
            },
        },
        {
            id: 'person-role-panel',
            type: 'shape',
            shapeType: 'rect',
            x: 112,
            y: 876,
            width: 860,
            height: 58,
            zIndex: 2,
            fill: {
                type: 'solid',
                value: '#f5f5f2',
            },
        },
        {
            id: 'person-accent-block',
            type: 'shape',
            shapeType: 'rect',
            x: 80,
            y: 792,
            width: 32,
            height: 142,
            zIndex: 3,
            fill: {
                type: 'solid',
                value: '#d71920',
            },
        },
        {
            id: 'person-name-text',
            type: 'text',
            x: 146,
            y: 810,
            width: 886,
            height: 52,
            zIndex: 4,
            fieldId: 'name',
            fallbackText: 'NUME PERSOANA',
            fitInBox: true,
            fitMode: 'scaleX',
            minScaleX: 0.62,
            textStyle: {
                fontFamily: 'Inter',
                fontSize: 48,
                fontWeight: 800,
                color: '#ffffff',
                align: 'left',
                transform: 'uppercase',
            },
        },
        {
            id: 'person-occupation-text',
            type: 'text',
            x: 146,
            y: 890,
            width: 786,
            height: 34,
            zIndex: 5,
            fieldId: 'occupation',
            fallbackText: 'Functie',
            fitInBox: true,
            fitMode: 'scaleX',
            minScaleX: 0.7,
            textStyle: {
                fontFamily: 'Inter',
                fontSize: 30,
                fontWeight: 600,
                color: '#173a73',
                align: 'left',
            },
        },
    ],
}
